import pandas as pd
import sys
import io

# Set encoding for stdout to utf-8
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

file_path = "Parts_DB_Detailed Definition.xlsx"

try:
    xl = pd.ExcelFile(file_path)
    sheet_names = xl.sheet_names
    
    # Define mapping and order
    targets = {
        'tb_Parts': '파츠 정보',
        'tb_PartsOptionGroup': '파츠 옵션 그룹',
        'tb_PartsOption': '파츠 옵션',
        'tb_PartsMainOption': '파츠 주 옵션',
        'tb_PartsSubOption': '파츠 부 옵션',
        'tb_PartsEnhance': '파츠 강화',
        'tb_Item': '아이템 테이블',
        'tb_UserParts': '유저 파츠',
        'tb_UserPartsOption': '유저 파츠 옵션',
        'tb_UserInventory': '유저 인벤토리',
        'tb_UserEquipParts': '유저 장착 파츠',
        'tb_PartsType': '파츠 타입 정보',
        'tb_Grade': '등급 정보',
        'tb_GroupType': '그룹 타입 정보',
        'tb_OptionGrade': '옵션 등급 정보'
    }
    
    toc_html = ""
    content_html = ""
    
    count = 1
    for sheet_id in targets.keys():
        if sheet_id in sheet_names:
            title = targets[sheet_id]
            df = pd.read_excel(file_path, sheet_name=sheet_id)
            df = df.dropna(how='all').fillna('')
            
            section_id = f"sec-4-2-{count}"
            section_num = f"4.2.{count}"
            
            # TOC entry
            toc_html += f'                            <li><a href="#{section_id}">{section_num}. {title}</a></li>\n'
            
            # Content entry
            content_html += f'            <h4 id="{section_id}" style="margin-top: 20px;">{section_num}. {title}</h4>\n'
            content_html += f'            <div style="margin-top: 10px;">\n'
            
            # Clean up the HTML table generated by pandas
            table_html = df.to_html(index=False, classes='code-table')
            table_html = table_html.replace(' border="1" class="dataframe code-table"', ' class="code-table"')
            # Also align header text better if needed, but the CSS handles it mostly
            
            content_html += f'                {table_html}\n'
            content_html += f'            </div>\n\n'
            
            count += 1

    print("--- TOC ---")
    print(toc_html)
    print("--- CONTENT ---")
    print(content_html)
            
except Exception as e:
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)
